# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.7.1.{build}
image: WMF 5
skip_commits:
  files:
   - '**/*.md'
   - .github/*

#---------------------------------#
#      environment configuration  #
#---------------------------------#

install:
- ps: >-
    Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\src\VSTeamBuilder.psd1").RequiredModules | ForEach-Object { Install-Module $PSItem.moduleName -RequiredVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }
- cinst pester
- cinst psake

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
- ps: >-
    Invoke-PSake $env:APPVEYOR_BUILD_FOLDER\build\build.psake.ps1 -taskList Test
    if ($psake.build_success -eq $false) { throw "Psake Build Failed. $($psake.error_message)"}
after_test:
- ps: >-
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $env:APPVEYOR_BUILD_FOLDER\release\PesterReport\Unit.TEST.xml))
# after_test:
#   - ps: |
#       $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
#       Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
#       bash codecov.sh -f "coverage.xml" -t YourUploadToken
branches:
  only:
  - dev
  - master
skip_tags: true


#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
# before_deploy:
#   - ps: hostname

# for:
# -
#   branches:
#     only:
#       - master

#   deploy:
#     - provider: Environment
#       name: Test PS Gallery
#       on:
#         appveyor_repo_tag: true
