# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 2.0.0{build}

skip_commits:
  files:
   - '**/*.md'
   - .github/*

#---------------------------------#
#      environment configuration  #
#---------------------------------#

install:
- ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
- ps: (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\src\VSTeamBuilder.psd1").RequiredModules | ForEach-Object { Install-Module $PSItem.moduleName -RequiredVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
- ps: build/build.ps1

branches:
  only:
  - dev
  - master

  skip_tags: true

deploy: off
